const FONTS = {
  amita: "'Amita', cursive",
  another: "'Just Another Hand', cursive",
  caveat: "'Caveat', cursive",
  caveatBrush: "'Caveat Brush', cursive",
  covered: "'Covered By Your Grace', cursive",
  didact: "'Didact Gothic', sans-serif",
  drSugiyama: "'Dr Sugiyama', cursive",
  gochi: "'Gochi Hand', cursive",
  hachi: "'Hachi Maru Pop', cursive",
  lato: "'Lato', sans-serif",
  longCang: "'Long Cang', cursive",
  mandrope: "'Manrope', sans-serif",
  mansalva: "'Mansalva', cursive",
  nothing: "'Nothing You Could Do', cursive",
  noto: "'Noto Sans TC', sans-serif",
  poppins: "'Poppins', sans-serif",
  questrial: "'Questrial', sans-serif",
  reenie: "'Reenie Beanie', cursive",
  satisfy: "'Satisfy', cursive",
  sed: "'Sedgwick Ave', cursive",
  sedDisplay: "'Sedgwick Ave Display', cursive",
  shep: "'Mrs Sheppards', cursive",
};

export default FONTS;
